[project]
name = "macro-finance-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fredapi>=0.5.2",
    "polars>=1.22.0",
    "yfinance>=0.2.52",
]
